server:
  port: 5501

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      routes:
        # =====================================
        - id: sso
          uri: lb://sso-service
          predicates:
            - Path=/sso/**
        # =====================================
        - id: storage
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
        # =====================================
        - id: crm
          uri: lb://crm-service
          predicates:
            - Path=/crm/**
        # =====================================
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
