server:
  port: 5501

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - '*'
              # DEV
              - 'https://khaiminhland-dev.innovation.com.vn'
              - 'http://192.168.1.94'
              - 'https://192.168.1.94'
              - 'http://192.168.1.91:5501/'
              - 'http://192.168.1.91:5504/'
              - 'http://192.168.1.91:5505/'
              - 'http://192.168.1.91:5506/'
              - 'http://192.168.1.91:5507/'
              - 'http://192.168.1.91:5508/'
              - 'http://192.168.1.91:5509/'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      routes:
        # =====================================
        - id: sso
          uri: lb://sso-service
          predicates:
            - Path=/sso/**
        # =====================================
        - id: storage
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
        # =====================================
        - id: crm
          uri: lb://crm-service
          predicates:
            - Path=/crm/**
        # =====================================
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
